# Generated by Django 3.2.4 on 2021-06-21 07:44

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_pizza_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t2', multiselectfield.db.fields.MultiSelectField(choices=[('Onion', 'Onion'), ('Tomato', 'Tomato'), ('Capsicum', 'Capsicum'), ('Corn', 'Corn'), ('Olives', 'Olives'), ('Jalepenos', 'Jalepenos'), ('Cheese', 'Cheese'), ('Paneer', 'Paneer'), ('Pickle', 'Pickle')], max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='t2',
            field=models.ManyToManyField(to='myapp.Toppings'),
        ),
    ]
