# Generated by Django 3.2.4 on 2021-06-21 07:52

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210621_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toppings',
            name='toppings',
        ),
        migrations.AddField(
            model_name='toppings',
            name='t2',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Onion', 'Onion'), ('Tomato', 'Tomato'), ('Capsicum', 'Capsicum'), ('Corn', 'Corn'), ('Olives', 'Olives'), ('Jalepenos', 'Jalepenos'), ('Cheese', 'Cheese'), ('Paneer', 'Paneer'), ('Pickle', 'Pickle')], max_length=64, null=True),
        ),
    ]
