# Generated by Django 3.2.4 on 2021-06-21 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210621_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='t2',
        ),
        migrations.DeleteModel(
            name='Toppings',
        ),
    ]
